settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: favicon.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  # - id: workers-cloudflare-com # unique identifier
  #   name: workers.cloudflare.com
  #   description: 'You write code. They handle the rest.' # default=empty
  #   url: 'https://workers.cloudflare.com/' # URL to fetch
  #   method: GET # default=GET
  #   expectStatus: 200 # operational status, default=200
  #   followRedirect: false # should fetch follow redirects, default=false
  #   linkable: false # allows the title to be a link, default=true
  - id: mlsb
    name: Bluesky.MLSB
    description: 'MLSB Bluesky Feed (Machine Learning in Structural Biology)'
    url: 'http://mlsb.ramith.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: labs
    name: labs.ramith.io
    description: 'Jupyter Notebooks.'
    url: 'http://labs.ramith.io'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  
  - id: static
    name: static.ramith.io
    description: 'Static.'
    url: 'http://static.ramith.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: selex
    name: selex.ramith.io
    description: 'SELEX.'
    url: 'http://selex.ramith.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
