name = "cf-workers-status-page"
workers_dev = true
main = "index.js"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "out"

[env.production]
kv_namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]